spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      metrics:
        enabled: true
      routes:
        - id: dummy-service
          uri: lb://dummy-service/
          predicates:
            - Path=/api/ds/**
        - id: dummy-service2
          uri: lb://dummy-service2/
          predicates:
            - Path=/api/ds2/**
#        - id: authorization-service
#          uri: lb://authorization-service/
#          predicates:
#            - Path=/api/auth/**
  security:
    oauth2:
      client:
        provider:
          microservice-auth-provider:
            issuer-uri: http://localhost:8080/realms/springboot-microservice-realm
        registration:
          microservice-auth:
            provider: microservice-auth-provider
            scope: openid
            client-id:
            client-secret:
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

