spring:
  cloud:
    gateway:
      metrics:
        enabled: true
      routes:
        - id: dummy-service
          uri: lb://dummy-service/
          predicates:
            - Path=/api/ds/**
#        - id: osm-data-rules
#          uri: lb://osm-data-rules/
#          predicates:
#            - Path=/api/odr/**


management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
