spring:
  cloud:
    gateway:
      metrics:
        enabled: true
      routes:
        - id: payment-service
          uri: lb://payment-service/
          predicates:
            - Path=/api/payment/**
        - id: appointment-service
          uri: lb://appointment-service/
          predicates:
            - Path=/api/appointment/**
        - id: doctor-app
          uri: lb://doctor-app/
          predicates:
            - Path=/api/doctor-app/**
#        - id: authorization-service
#          uri: lb://authorization-service/
#          predicates:
#            - Path=/api/auth/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/doctor-app-realm
