spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      metrics:
        enabled: true
      routes:
        - id: dummy-service
          uri: lb://dummy-service/
          predicates:
            - Path=/api/dummy/**
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  application:
    name: gateway-service

server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

