spring:
  cloud:
    gateway:
      metrics:
        enabled: true
      routes:
        - id: dummy-service
          uri: lb://dummy-service/
          predicates:
            - Path=/api/ds/**
        - id: dummy-service2
          uri: lb://dummy-service2/
          predicates:
            - Path=/api/ds2/**
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
