spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: dummy-service
          uri: lb://dummy-service
          predicates:
            - Path=/api/dummy/**
        - id: dummy-service2
          uri: lb://dummy-service2
          predicates:
            - Path=/api/dummy2/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
  application:
    name: api-gateway

server:
  port: 9999

logging:
  level:
    root: INFO
