spring:
  cloud:
    config:
      uri: http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/doctor-app-realm
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: pgtest
    password: pgtest
    driver-class-name: org.postgresql.Driver

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 9000


microservice:
  retrievePatientsInformationUrl: "http://doctor-app:8500/api/doctor-app/info/patient/retrieve-patient-info"
  retrieveDoctorsInformationUrl:  "http://doctor-app:8500/api/doctor-app/info/doctor/retrieve-doctor-info"
  addPaymentUrl: "http://payment-service:9999/api/payment/add"